package Beans;
// Generated 09-mar-2009 10:54:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Juegos generated by hbm2java
 */
public class Juegos  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private int jugadoresmin;
     private String reglas;
     private Set salases = new HashSet(0);

    public Juegos() {
    }

	
    public Juegos(int codigo, String nombre, int jugadoresmin) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.jugadoresmin = jugadoresmin;
    }
    public Juegos(int codigo, String nombre, int jugadoresmin, String reglas, Set salases) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.jugadoresmin = jugadoresmin;
       this.reglas = reglas;
       this.salases = salases;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getJugadoresmin() {
        return this.jugadoresmin;
    }
    
    public void setJugadoresmin(int jugadoresmin) {
        this.jugadoresmin = jugadoresmin;
    }
    public String getReglas() {
        return this.reglas;
    }
    
    public void setReglas(String reglas) {
        this.reglas = reglas;
    }
    public Set getSalases() {
        return this.salases;
    }
    
    public void setSalases(Set salases) {
        this.salases = salases;
    }




}


