package Beans;
// Generated 09-mar-2009 10:54:47 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Mesas generated by hbm2java
 */
public class Mesas  implements java.io.Serializable {


     private BigDecimal codigo;
     private Salas salas;
     private BigDecimal puestos;
     private BigDecimal jugadores;
     private BigDecimal apuestamin;
     private BigDecimal apuestamax;
     private Set partidases = new HashSet(0);

    public Mesas() {
    }

	
    public Mesas(BigDecimal codigo, Salas salas, BigDecimal puestos, BigDecimal jugadores, BigDecimal apuestamin, BigDecimal apuestamax) {
        this.codigo = codigo;
        this.salas = salas;
        this.puestos = puestos;
        this.jugadores = jugadores;
        this.apuestamin = apuestamin;
        this.apuestamax = apuestamax;
    }
    public Mesas(BigDecimal codigo, Salas salas, BigDecimal puestos, BigDecimal jugadores, BigDecimal apuestamin, BigDecimal apuestamax, Set partidases) {
       this.codigo = codigo;
       this.salas = salas;
       this.puestos = puestos;
       this.jugadores = jugadores;
       this.apuestamin = apuestamin;
       this.apuestamax = apuestamax;
       this.partidases = partidases;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public BigDecimal getPuestos() {
        return this.puestos;
    }
    
    public void setPuestos(BigDecimal puestos) {
        this.puestos = puestos;
    }
    public BigDecimal getJugadores() {
        return this.jugadores;
    }
    
    public void setJugadores(BigDecimal jugadores) {
        this.jugadores = jugadores;
    }
    public BigDecimal getApuestamin() {
        return this.apuestamin;
    }
    
    public void setApuestamin(BigDecimal apuestamin) {
        this.apuestamin = apuestamin;
    }
    public BigDecimal getApuestamax() {
        return this.apuestamax;
    }
    
    public void setApuestamax(BigDecimal apuestamax) {
        this.apuestamax = apuestamax;
    }
    public Set getPartidases() {
        return this.partidases;
    }
    
    public void setPartidases(Set partidases) {
        this.partidases = partidases;
    }




}


