package Beans;
// Generated 09-mar-2009 10:54:47 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Partidas generated by hbm2java
 */
public class Partidas  implements java.io.Serializable {


     private BigDecimal codigo;
     private Mesas mesas;
     private BigDecimal numjugadores;
     private BigDecimal ganador;
     private Set clienteses = new HashSet(0);

    public Partidas() {
    }

	
    public Partidas(BigDecimal codigo, Mesas mesas, BigDecimal numjugadores, BigDecimal ganador) {
        this.codigo = codigo;
        this.mesas = mesas;
        this.numjugadores = numjugadores;
        this.ganador = ganador;
    }
    public Partidas(BigDecimal codigo, Mesas mesas, BigDecimal numjugadores, BigDecimal ganador, Set clienteses) {
       this.codigo = codigo;
       this.mesas = mesas;
       this.numjugadores = numjugadores;
       this.ganador = ganador;
       this.clienteses = clienteses;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Mesas getMesas() {
        return this.mesas;
    }
    
    public void setMesas(Mesas mesas) {
        this.mesas = mesas;
    }
    public BigDecimal getNumjugadores() {
        return this.numjugadores;
    }
    
    public void setNumjugadores(BigDecimal numjugadores) {
        this.numjugadores = numjugadores;
    }
    public BigDecimal getGanador() {
        return this.ganador;
    }
    
    public void setGanador(BigDecimal ganador) {
        this.ganador = ganador;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


