package Beans;
// Generated 09-mar-2009 10:24:16 by Hibernate Tools 3.2.1.GA



/**
 * Participantes generated by hbm2java
 */
public class Participantes  implements java.io.Serializable {


     private ParticipantesId id;

    public Participantes() {
    }

    public Participantes(ParticipantesId id) {
       this.id = id;
    }
   
    public ParticipantesId getId() {
        return this.id;
    }
    
    public void setId(ParticipantesId id) {
        this.id = id;
    }




}


