package Beans;
// Generated 09-mar-2009 10:24:16 by Hibernate Tools 3.2.1.GA



/**
 * Participantes generated by hbm2java
 */
public class Participantes  implements java.io.Serializable {

     private int partida;
     private int jugador;

    public Participantes() {
    }

    public Participantes(int partida, int jugador) {
       this.partida = partida;
       this.jugador = jugador;
    }
   
    public int getPartida() {
        return this.partida;
    }
    
    public void setPartida(int partida) {
        this.partida = partida;
    }
    public int getJugador() {
        return this.jugador;
    }
    
    public void setJugador(int jugador) {
        this.jugador = jugador;
    }



}


