/*
 * FrameUso.java
 *
 * Created on 03-may-2009, 22:23:11
 */

package vista;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;

/**
 *
 * @author GabiPC
 */
public class VistaRuletaTemp extends javax.swing.JFrame {

    /** Creates new form FrameUso */
    public VistaRuletaTemp() {
        initComponents();
        mesa = new MesaPanel();
        //getContentPane().add(mesa);
        mesa.setBounds(365, 0, 430, 800);
        //mesa.setBounds(565, 0, 430, 800);
        jLayeredPane1.add(mesa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.moveToFront(mesa);
    }

	public void paint(Graphics g) {
        if(gira){
        if(ImagenRuleta==null)
              ImagenRuleta = loadImage("./recursos/ruleta.png");
        if(ImagenBola==null)
              ImagenBola = loadImage("./recursos/bola.png");
        //g.setColor(getBackground());
        Graphics2D g2 = (Graphics2D)g;
        Graphics2D g3 = (Graphics2D)g;
        for(int i=0;i<256*numVueltas;i++){
            g2.rotate(Math.PI/128.0,575,167);
            g2.drawImage(ImagenRuleta, 497, 89,this);
             try {
                  Thread.sleep(1);
              } catch (InterruptedException e) {}
        }
        g3.drawImage(ImagenBola,bolaX,bolaY,this);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelChat1 = new vista.JPanelChat();
        jPanelCjtoApuestasTemp1 = new vista.JPanelCjtoApuestasTemp();
        jPanelUsuariosTemp1 = new vista.JPanelUsuariosTemp();
        jButtonBack = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setOpaque(true);
        jPanelChat1.setBounds(0, 230, 357, 179);
        jLayeredPane1.add(jPanelChat1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelCjtoApuestasTemp1.setBounds(190, 440, 150, 200);
        jLayeredPane1.add(jPanelCjtoApuestasTemp1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelUsuariosTemp1.setBounds(20, 440, 150, 200);
        jLayeredPane1.add(jPanelUsuariosTemp1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonBack.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\GabiPC\\Escritorio\\II\\Practica IS\\Repositorio\\Cliente\\trunk\\ClienteCasino\\recursos\\3flecha_izquierda-cubeg1-thumb.gif")); // NOI18N
        jButtonBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBack.setLabel("Volver");
        jButtonBack.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButtonBack.setBounds(40, 660, 73, 80);
        jLayeredPane1.add(jButtonBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonSalir.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\GabiPC\\Escritorio\\II\\Practica IS\\Repositorio\\Cliente\\trunk\\ClienteCasino\\recursos\\TgC_boton142.gif")); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButtonSalir.setBounds(260, 660, 73, 80);
        jLayeredPane1.add(jButtonSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanelDatos.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");

        jLabelUsuario.setFont(new java.awt.Font("Century Gothic", 1, 16));
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Saldo actual");

        jLabelSaldo.setFont(new java.awt.Font("Century Gothic", 1, 16));
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSaldo.setText("Leuros");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("5 Segundos restantes");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelDatos.setBounds(50, 20, 280, 190);
        jLayeredPane1.add(jPanelDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(150, 660, 73, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("jButton2");
        jButton2.setBounds(150, 700, 73, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        girarRuleta(22);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUso().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLayeredPane jLayeredPane1;
    private vista.JPanelChat jPanelChat1;
    private vista.JPanelCjtoApuestasTemp jPanelCjtoApuestasTemp1;
    private javax.swing.JPanel jPanelDatos;
    private vista.JPanelUsuariosTemp jPanelUsuariosTemp1;
    // End of variables declaration
	private BufferedImage ImagenRuleta = null;
	private BufferedImage ImagenBola = null;
	private boolean gira=false;
	private MesaPanel mesa;
	private int bolaX, bolaY;
	private static int numVueltas = 3;

    private BufferedImage loadImage(String string) {
       URL url=null;
       try { // url = getClass().getClassLoader().getResource(string);
       return ImageIO.read(new File(string));
       } catch (Exception e) {
           System.out.println("No se pudo cargar la imagen " + string +" de "+url);
           System.out.println("El error fue : "+e.getClass().getName()+" "+e.getMessage());
           System.exit(0);
           return null;
       }
    }

    public void girarRuleta(int numRuleta) {


		switch (numRuleta){

			case 22 :  bolaX=525;
					   bolaY=120;
					   break;
			case 18 :  bolaX=530;
					   bolaY=115;
					   break;
			case 29 :  bolaX=543;
					   bolaY=110;
					   break;
			case 7  :  bolaX=553;
					   bolaY=107;
					   break;
			case 28 :  bolaX=563;
			   		   bolaY=107;
			   		   break;
			case 12 :  bolaX=573;
	   		   		   bolaY=107;
	   		   		   break;
			case 35 :  bolaX=580;
	   		   		   bolaY=107;
	   		   		   break;
			case 3  :  bolaX=590;
	   		   		   bolaY=110;
	   		   		   break;
			case 26 :  bolaX=596;
					   bolaY=115;
					   break;
			case 0  :  bolaX=607;
			   		   bolaY=117;
			   		   break;
			case 32 :  bolaX=614;
	   		   		   bolaY=124;
	   		   		   break;
			case 15 :  bolaX=618;
					   bolaY=132;
					   break;
			case 19 :  bolaX=620;
					   bolaY=142;
					   break;
			case 4  :  bolaX=623;
			   		   bolaY=152;
			   		   break;
			case 21 :  bolaX=624;
	   		   		   bolaY=162;
	   		   		   break;
			case 2  :  bolaX=624;
	   		   		   bolaY=172;
	   		   		   break;
			case 25 :  bolaX=624;
	   		   		   bolaY=182;
	   		   		   break;
			case 17 :  bolaX=622;
	   		   		   bolaY=190;
	   		   		   break;
			case 34 :  bolaX=614;
	   		   		   bolaY=196;
	   		           break;
			case  6 :  bolaX=610;
	   		   		   bolaY=207;
	   		   		   break;
			case  27:  bolaX=600;
	   		   		   bolaY=207;
	   		   		   break;
			case  13:  bolaX=590;
	   		   bolaY=210;
	   		   break;
			case  36:  bolaX=580;
	   		   bolaY=215;
	   		   break;
			case  11:  bolaX=570;
	   		   bolaY=216;
	   		   break;
			case  30:  bolaX=562;
	   		   bolaY=216;
	   		   break;
			case  8 :  bolaX=554;
	   		   bolaY=216;
	   		   break;
			case  23 :  bolaX=544;
	   		   bolaY=216;
	   		   break;
			case  10 :  bolaX=532;
	   		   bolaY=210;
	   		   break;
			case  5 :  bolaX=527;
	   		   bolaY=203;
	   		   break;
			case  24 :  bolaX=523;
	   		   bolaY=193;
	   		   break;
			case  16 :  bolaX=518;
	   		   			bolaY=186;
	   		   			break;
			case  33 :  bolaX=516;
	   			bolaY=177;
	   			break;
			case  1 :  bolaX=516;
   			bolaY=166;
   			break;
			case  20 :  bolaX=516;
   						bolaY=155;
   						break;
			case  14 :  bolaX=516;
				bolaY=145;
				break;
			case  31 :  bolaX=518;
			bolaY=135;
			break;
			case  9 :  bolaX=522;
			bolaY=130;
			break;
		}
		gira=true;
		repaint();

	}

}
