/*
 * PartidaRuleta.java
 *
 * Created on 29 de noviembre de 2008, 15:36
 */
package InterfazCliente;

import servidorcasino.Servidor;
//import servidorcasino.ApuestaRuleta;
import Casilla.Numero;
import java.awt.Color;
/**
 *
 * @author  Chaudhary
 */
public class Ruleta extends javax.swing.JFrame {

    Servidor servidor = null;
    int totalApostado = 0;
    int apuestaIndividual = 10;
    String mensajes = "";

    /** Creates new form PartidaRuleta */
    public Ruleta() {
        initComponents();
        this.setVisible(false);
    }

    /**
     * Muestra el formulario
     */
    public void muestra() {
        this.setVisible(true);
    }

    public void registraServidor(Servidor server) {
        this.servidor = server;
    }

    public void incluirMensaje(String msg) {
        if (mensajes == "") {
            mensajes = msg;
        } else {
            mensajes += "\n" + msg;
        }
        this.panelMensaje.setText(mensajes);

    }
    public void actualizaSaldo(int nuevosaldo){
        saldo.setText(Integer.toString(nuevosaldo));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLanzarBola = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMensaje = new javax.swing.JTextPane();
        btn0 = new javax.swing.JButton();
        fieldCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRojo = new javax.swing.JButton();
        btnNegro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        bola = new javax.swing.JLabel();
        COLOR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setText("APUESTAS");

        btnLanzarBola.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnLanzarBola.setText("Lanzar Bola");
        btnLanzarBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarBolaActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setText("10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setText("11");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setText("12");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setText("13");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn14.setText("14");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn15.setText("15");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setText("16");
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        btn17.setText("17");
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });

        btn18.setText("18");
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });

        btn19.setText("19");
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });

        btn20.setText("20");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setText("21");
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setText("22");
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn23.setText("23");
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        btn24.setText("24");
        btn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn24ActionPerformed(evt);
            }
        });

        btn25.setText("25");
        btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25ActionPerformed(evt);
            }
        });

        btn26.setText("26");
        btn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn26ActionPerformed(evt);
            }
        });

        btn27.setText("27");
        btn27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn27ActionPerformed(evt);
            }
        });

        btn28.setText("28");
        btn28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn28ActionPerformed(evt);
            }
        });

        btn29.setText("29");
        btn29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn29ActionPerformed(evt);
            }
        });

        btn30.setText("30");
        btn30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30ActionPerformed(evt);
            }
        });

        btn31.setText("31");
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });

        btn32.setText("32");
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });

        btn33.setText("33");
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });

        btn34.setText("34");
        btn34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn34ActionPerformed(evt);
            }
        });

        btn35.setText("35");
        btn35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn35ActionPerformed(evt);
            }
        });

        btn36.setText("36");
        btn36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn36ActionPerformed(evt);
            }
        });

        jLabel2.setText("Mensajes del Casino:");

        jScrollPane1.setViewportView(panelMensaje);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        fieldCantidad.setColumns(6);

        jLabel3.setText("Cantidad a Apostar:");

        btnRojo.setBackground(new java.awt.Color(255, 51, 51));
        btnRojo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRojo.setForeground(new java.awt.Color(255, 255, 255));
        btnRojo.setText("ROJO");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnNegro.setBackground(new java.awt.Color(0, 0, 0));
        btnNegro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNegro.setForeground(new java.awt.Color(255, 255, 255));
        btnNegro.setText("NEGRO");
        btnNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegroActionPerformed(evt);
            }
        });

        jLabel4.setText("Saldo:");

        saldo.setText("0");

        bola.setText("-");

        COLOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLORActionPerformed(evt);
            }
        });

        jLabel5.setText("ULTIMA BOLA");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(btnLanzarBola, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(fieldCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(132, 132, 132)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(saldo)
                                .add(1, 1, 1)))
                        .add(40, 40, 40))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel5)
                            .add(bola, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(COLOR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(btn1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(btn7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(btn13))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(btn14)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btn15)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btn16)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btn17)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btn18))
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(btn2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(btn8))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(layout.createSequentialGroup()
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(btn3)
                                                            .add(btn9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(layout.createSequentialGroup()
                                                                .add(2, 2, 2)
                                                                .add(btn10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(btn11)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(btn12))
                                                            .add(layout.createSequentialGroup()
                                                                .add(btn4)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(btn5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                                .add(btn6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                                    .add(layout.createSequentialGroup()
                                                        .add(12, 12, 12)
                                                        .add(btn0)
                                                        .add(18, 18, 18)
                                                        .add(btnRojo)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(btnNegro))))))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(btn19)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn20)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn21)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn22)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn23)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn24))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(btn25)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn26)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn27)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn28)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn29)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn30))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(btn31)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn32)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn33)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn34)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn35)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btn36)))
                                .add(20, 20, 20)))))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {btn1, btn10, btn11, btn12, btn13, btn14, btn15, btn16, btn17, btn18, btn19, btn2, btn20, btn21, btn22, btn23, btn24, btn25, btn26, btn27, btn28, btn29, btn3, btn30, btn31, btn32, btn33, btn34, btn35, btn36, btn4, btn5, btn6, btn7, btn8, btn9}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn1)
                            .add(btn2)
                            .add(btn3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn7)
                            .add(btn8)
                            .add(btn9)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnRojo)
                            .add(btnNegro)
                            .add(btn0))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn4)
                            .add(btn5)
                            .add(btn6))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn10)
                            .add(btn11)
                            .add(btn12))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn13)
                    .add(btn14)
                    .add(btn15)
                    .add(btn16)
                    .add(btn17)
                    .add(btn18))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn19)
                    .add(btn20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btn36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fieldCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(btnLanzarBola, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(saldo)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bola, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(COLOR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(35, 35, 35)))
                .add(51, 51, 51))
        );

        layout.linkSize(new java.awt.Component[] {btn1, btn10, btn11, btn12, btn13, btn14, btn15, btn16, btn17, btn18, btn19, btn2, btn20, btn21, btn22, btn23, btn24, btn25, btn26, btn27, btn28, btn29, btn3, btn30, btn31, btn32, btn33, btn34, btn35, btn36, btn4, btn5, btn6, btn7, btn8, btn9}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnLanzarBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarBolaActionPerformed
    /*
     * Llama a la funcion para tirar la bola 
    */
    int i= servidor.nuevaTirada();
    String saldoDevuelto=""+i;
    saldo.setText(saldoDevuelto);
    Numero n=servidor.dameBola();
    String bolaLanzada=""+n.getNumero();
    bola.setText(bolaLanzada); 
    if (n.getColor().equals("ROJO")) COLOR.setBackground(new Color(255, 0, 0)); 
    else COLOR.setBackground(new Color(0, 0, 0));

}//GEN-LAST:event_btnLanzarBolaActionPerformed

private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",2, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn2ActionPerformed

private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
   String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",1, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn1ActionPerformed

private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",3, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn3ActionPerformed

private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",4, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn4ActionPerformed

private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",5, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn5ActionPerformed

private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",6, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn6ActionPerformed

private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",7, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn7ActionPerformed

private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",8, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn8ActionPerformed

private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",9, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn9ActionPerformed

private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",10, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn10ActionPerformed

private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",11, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn11ActionPerformed

private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",12, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn12ActionPerformed

private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",13, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn13ActionPerformed

private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",14, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn14ActionPerformed

private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",15, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn15ActionPerformed

private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",16, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn16ActionPerformed

private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",17, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn17ActionPerformed

private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",18, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn18ActionPerformed

private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",19, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn19ActionPerformed

private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",20, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn20ActionPerformed

private void btn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn24ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",24, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn24ActionPerformed

private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",21, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn21ActionPerformed

private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",22, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn22ActionPerformed

private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",23, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn23ActionPerformed

private void btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",25, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn25ActionPerformed

private void btn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn26ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",26, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn26ActionPerformed

private void btn27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn27ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",27, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");

}//GEN-LAST:event_btn27ActionPerformed

private void btn28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn28ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",28, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn28ActionPerformed

private void btn29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn29ActionPerformed
    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",29, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn29ActionPerformed

private void btn30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",30, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn30ActionPerformed

private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",31, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn31ActionPerformed

private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed

     String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",32, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn32ActionPerformed

private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed

    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",33, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btn33ActionPerformed

private void btn34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn34ActionPerformed

     String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",34, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
    
}//GEN-LAST:event_btn34ActionPerformed

private void btn35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn35ActionPerformed

      String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",35, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
    
}//GEN-LAST:event_btn35ActionPerformed

private void btn36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn36ActionPerformed

     String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",36, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
    
}//GEN-LAST:event_btn36ActionPerformed

private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("numero",0, apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
    
}//GEN-LAST:event_btn0ActionPerformed

private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
   String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("PARIMPAR","ROJO", apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btnRojoActionPerformed

private void btnNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegroActionPerformed
    String cantidad=fieldCantidad.getText();
    if (!cantidad.equals("")){
    int apuestaActual =Integer.parseInt(cantidad,10);
    totalApostado += apuestaActual;
    servidor.nuevaJugada("PARIMPAR","NEGRO", apuestaActual);
    }
    else incluirMensaje("Cantidad no valida");
}//GEN-LAST:event_btnNegroActionPerformed

private void COLORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLORActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_COLORActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ruleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COLOR;
    private javax.swing.JLabel bola;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnLanzarBola;
    private javax.swing.JButton btnNegro;
    private javax.swing.JButton btnRojo;
    private javax.swing.JTextField fieldCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextPane panelMensaje;
    private javax.swing.JLabel saldo;
    // End of variables declaration//GEN-END:variables
}
