package bbdd.beans;
// Generated 09-mar-2009 10:54:47 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Partidas generated by hbm2java
 */
public class Partidas  implements java.io.Serializable {


     private int codigo;
     private Mesas mesas;
     private int numjugadores;
     private int ganador;
     private Set clienteses = new HashSet(0);

    public Partidas() {
    }

	
    public Partidas(int codigo, Mesas mesas, int numjugadores, int ganador) {
        this.codigo = codigo;
        this.mesas = mesas;
        this.numjugadores = numjugadores;
        this.ganador = ganador;
    }
    public Partidas(int codigo, Mesas mesas, int numjugadores, int ganador, Set clienteses) {
       this.codigo = codigo;
       this.mesas = mesas;
       this.numjugadores = numjugadores;
       this.ganador = ganador;
       this.clienteses = clienteses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Mesas getMesas() {
        return this.mesas;
    }
    
    public void setMesas(Mesas mesas) {
        this.mesas = mesas;
    }
    public int getNumjugadores() {
        return this.numjugadores;
    }
    
    public void setNumjugadores(int numjugadores) {
        this.numjugadores = numjugadores;
    }
    public int getGanador() {
        return this.ganador;
    }
    
    public void setGanador(int ganador) {
        this.ganador = ganador;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }




}


